version: '3.8'

services:
  frontend:
    build:
      context: ./client
      target: development
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - fit-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fitview_backend
    volumes:
      - ./server:/app
      - /app/.venv
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGCHANNELBINDING=${PGCHANNELBINDING}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
    networks:
      - fit-network

  adminer:
    image: adminer
    container_name: fitview_adminer
    ports:
      - "8080:8080"
    networks:
      - fit-network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fit-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - fit-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - fit-network


networks:
  fit-network:
    driver: bridge

