server {
    listen 80;

        # Для статики, если нужно (например, для админки Django)
    location /static/ {
    alias /var/www/static/;
    }

    # Фронтенд
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Бэкенд API
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Для работы hot reload (WebSocket) во время разработки
    location /@vite/ {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
