"""add 'size_label' field to the cart_items table

Revision ID: 1246b2a9bf7d
Revises: 4d24ec0481b2
Create Date: 2026-04-14 17:53:39.720429

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1246b2a9bf7d"
down_revision: Union[str, Sequence[str], None] = "4d24ec0481b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_items", sa.Column("size_label", sa.String(length=10), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_items", "size_label")
    # ### end Alembic commands ###
