"""set 'user_id' and 'item_id' fields nullable in FitviewEventsModel

Revision ID: 34fb5dedc833
Revises: b66fbb3992b6
Create Date: 2026-05-10 14:49:56.301621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34fb5dedc833"
down_revision: Union[str, Sequence[str], None] = "b66fbb3992b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fitview_events", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "fitview_events", "item_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fitview_events", "item_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "fitview_events", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
