"""add hips_length & breast_length to the ProfileModel, add hips_min_cm & hips_max_cm to the SizeChartModel

Revision ID: 35215af0aae8
Revises: 88319c25ecbc
Create Date: 2026-04-09 19:12:45.185178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35215af0aae8'
down_revision: Union[str, Sequence[str], None] = '88319c25ecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size_charts', sa.Column('hips_min_cm', sa.Float(), nullable=True))
    op.add_column('size_charts', sa.Column('hips_max_cm', sa.Float(), nullable=True))
    op.alter_column('size_charts', 'waist_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('size_charts', 'waist_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('size_charts', 'breast_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('size_charts', 'breast_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('size_charts', 'shoulders_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('size_charts', 'shoulders_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_size_charts_breast_max_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_breast_min_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_shoulders_max_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_shoulders_min_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_waist_max_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_waist_min_cm'), table_name='size_charts')
    op.add_column('user_profiles', sa.Column('hips_length_cm', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('breast_length_cm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'breast_length_cm')
    op.drop_column('user_profiles', 'hips_length_cm')
    op.create_index(op.f('ix_size_charts_waist_min_cm'), 'size_charts', ['waist_min_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_waist_max_cm'), 'size_charts', ['waist_max_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_shoulders_min_cm'), 'size_charts', ['shoulders_min_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_shoulders_max_cm'), 'size_charts', ['shoulders_max_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_breast_min_cm'), 'size_charts', ['breast_min_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_breast_max_cm'), 'size_charts', ['breast_max_cm'], unique=False)
    op.alter_column('size_charts', 'shoulders_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('size_charts', 'shoulders_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('size_charts', 'breast_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('size_charts', 'breast_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('size_charts', 'waist_max_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('size_charts', 'waist_min_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('size_charts', 'hips_max_cm')
    op.drop_column('size_charts', 'hips_min_cm')
    # ### end Alembic commands ###
