"""Add 'brands' table, add 'price' field to the 'items' table, fix field types

Revision ID: 523f67f944a5
Revises: edfd5a4e2a6c
Create Date: 2026-04-06 15:46:20.709232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523f67f944a5'
down_revision: Union[str, Sequence[str], None] = 'edfd5a4e2a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.add_column('items', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('price', sa.DECIMAL(), nullable=False))
    op.drop_index(op.f('ix_items_brand'), table_name='items')
    op.create_foreign_key(None, 'items', 'brands', ['brand_id'], ['id'])
    op.drop_column('items', 'brand')
    op.alter_column('size_charts', 'waist_min_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('size_charts', 'waist_max_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('size_charts', 'breast_min_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('size_charts', 'breast_max_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('size_charts', 'shoulders_min_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('size_charts', 'shoulders_max_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size_charts', 'shoulders_max_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('size_charts', 'shoulders_min_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('size_charts', 'breast_max_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('size_charts', 'breast_min_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('size_charts', 'waist_max_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('size_charts', 'waist_min_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('items', sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index(op.f('ix_items_brand'), 'items', ['brand'], unique=False)
    op.drop_column('items', 'price')
    op.drop_column('items', 'brand_id')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
