"""add 'ab_group' field to UserModel

Revision ID: 77ce58ecda6d
Revises: 1711cafd7102
Create Date: 2026-04-10 16:21:43.650929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ce58ecda6d'
down_revision: Union[str, Sequence[str], None] = '1711cafd7102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ab_group', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ab_group')
    # ### end Alembic commands ###
