"""added 'is_active' field to the 'users' table

Revision ID: 785b1e930556
Revises: 1246b2a9bf7d
Create Date: 2026-04-16 15:06:09.926778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "785b1e930556"
down_revision: Union[str, Sequence[str], None] = "1246b2a9bf7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_cart_item_size", "cart_items", ["cart_id", "item_id", "size_label"]
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_constraint("uix_cart_item_size", "cart_items", type_="unique")
    # ### end Alembic commands ###
