"""updated 'price' decimal field

Revision ID: 88319c25ecbc
Revises: 523f67f944a5
Create Date: 2026-04-06 16:04:32.594394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88319c25ecbc'
down_revision: Union[str, Sequence[str], None] = '523f67f944a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_unique_constraint('uix_items', 'items', ['name', 'brand_id', 'category'])
    op.create_unique_constraint('uix_item_size_chart', 'size_charts', ['item_id', 'size_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_item_size_chart', 'size_charts', type_='unique')
    op.drop_constraint('uix_items', 'items', type_='unique')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    # ### end Alembic commands ###
