"""initial schema

Revision ID: 8bb67021dabe
Revises: 
Create Date: 2026-04-11 18:10:04.996769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb67021dabe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'MANAGER', 'ADMIN', name='userroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ab_group', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('DRESS', 'SKIRT', 'T_SHIRT', 'BLOUSE', 'PANTS', 'SHIRT', name='itemcategoryenum'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNISEX', name='genderenum'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reference_point', sa.Enum('SHOULDERS', 'WAIST', 'CROTCH', name='itemrefpointenum'), nullable=False),
    sa.Column('ref_coefficient', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'brand_id', 'category', name='uix_items')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_gender'), 'items', ['gender'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNISEX', name='genderenum'), nullable=False),
    sa.Column('leg_length_cm', sa.Integer(), nullable=False),
    sa.Column('waist_length_cm', sa.Integer(), nullable=False),
    sa.Column('hips_length_cm', sa.Integer(), nullable=False),
    sa.Column('breast_length_cm', sa.Integer(), nullable=False),
    sa.Column('shoulders_length_cm', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('used_fitview', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('fitview_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('WIDGET_SHOWN', 'HEIGHT_ENTERED', 'RESULT_SHOWN', name='eventtypeenum'), nullable=False),
    sa.Column('height_used_cm', sa.Float(), nullable=True),
    sa.Column('result_end_cm', sa.Float(), nullable=True),
    sa.Column('fit_shoulders', sa.Enum('TIGHT', 'PERFECT', 'LOOSE', name='fitresultenum'), nullable=True),
    sa.Column('fit_breast', sa.Enum('TIGHT', 'PERFECT', 'LOOSE', name='fitresultenum'), nullable=True),
    sa.Column('fit_waist', sa.Enum('TIGHT', 'PERFECT', 'LOOSE', name='fitresultenum'), nullable=True),
    sa.Column('fit_hips', sa.Enum('TIGHT', 'PERFECT', 'LOOSE', name='fitresultenum'), nullable=True),
    sa.Column('ab_group', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitview_events_id'), 'fitview_events', ['id'], unique=False)
    op.create_table('item_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('total_length_cm', sa.Float(), nullable=False),
    sa.Column('inseam_cm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_measurements_id'), 'item_measurements', ['id'], unique=False)
    op.create_table('size_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('hips_min_cm', sa.Float(), nullable=True),
    sa.Column('hips_max_cm', sa.Float(), nullable=True),
    sa.Column('waist_min_cm', sa.Float(), nullable=True),
    sa.Column('waist_max_cm', sa.Float(), nullable=True),
    sa.Column('breast_min_cm', sa.Float(), nullable=True),
    sa.Column('breast_max_cm', sa.Float(), nullable=True),
    sa.Column('shoulders_min_cm', sa.Float(), nullable=True),
    sa.Column('shoulders_max_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'size_label', name='uix_item_size_chart')
    )
    op.create_index(op.f('ix_size_charts_id'), 'size_charts', ['id'], unique=False)
    op.create_index(op.f('ix_size_charts_item_id'), 'size_charts', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_charts_item_id'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_id'), table_name='size_charts')
    op.drop_table('size_charts')
    op.drop_index(op.f('ix_item_measurements_id'), table_name='item_measurements')
    op.drop_table('item_measurements')
    op.drop_index(op.f('ix_fitview_events_id'), table_name='fitview_events')
    op.drop_table('fitview_events')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_gender'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
