"""added fitting_image_url field to ItemsModel

Revision ID: b66fbb3992b6
Revises: e8b3998189b0
Create Date: 2026-04-27 21:54:18.312157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b66fbb3992b6"
down_revision: Union[str, Sequence[str], None] = "e8b3998189b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("fitting_image_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "fitting_image_url")
    # ### end Alembic commands ###
