"""added 'shoulders_length_cm' field to the 'user_profiles', added 'fit_shoulders', 'fit_breast', 'fit_waist', 'fit_hips' fields to the 'fitview_events' table

Revision ID: bf43f9210803
Revises: 35215af0aae8
Create Date: 2026-04-09 21:26:03.900372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf43f9210803'
down_revision: Union[str, Sequence[str], None] = '35215af0aae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitview_events', sa.Column('fit_shoulders', sa.String(length=10), nullable=False))
    op.add_column('fitview_events', sa.Column('fit_breast', sa.String(length=10), nullable=False))
    op.add_column('fitview_events', sa.Column('fit_waist', sa.String(length=10), nullable=False))
    op.add_column('fitview_events', sa.Column('fit_hips', sa.String(length=10), nullable=False))
    op.alter_column('fitview_events', 'event_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('fitview_events', 'height_used_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fitview_events', 'result_end_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fitview_events', 'ab_group',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_column('fitview_events', 'result_label')
    op.add_column('user_profiles', sa.Column('shoulders_length_cm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'shoulders_length_cm')
    op.add_column('fitview_events', sa.Column('result_label', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('fitview_events', 'ab_group',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('fitview_events', 'result_end_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fitview_events', 'height_used_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fitview_events', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('fitview_events', 'fit_hips')
    op.drop_column('fitview_events', 'fit_waist')
    op.drop_column('fitview_events', 'fit_breast')
    op.drop_column('fitview_events', 'fit_shoulders')
    # ### end Alembic commands ###
