"""removed nullable=True from ItemsModels.fitting_image_url

Revision ID: c59f602f73b2
Revises: 34fb5dedc833
Create Date: 2026-05-14 22:49:58.851941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c59f602f73b2"
down_revision: Union[str, Sequence[str], None] = "34fb5dedc833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
