"""added first_name, last_name, phone_number, birth_date to user_profiles table

Revision ID: c6d1c33c4fed
Revises: b31bc9e57d1c
Create Date: 2026-04-21 20:59:39.074886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6d1c33c4fed"
down_revision: Union[str, Sequence[str], None] = "b31bc9e57d1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("last_name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("phone_number", sa.String(length=50), nullable=False)
    )
    op.add_column("user_profiles", sa.Column("birth_date", sa.Date(), nullable=True))
    op.alter_column(
        "user_profiles", "height_cm", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_profiles", "leg_length_cm", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_profiles", "waist_length_cm", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_profiles", "hips_length_cm", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_profiles", "breast_length_cm", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_profiles",
        "shoulders_length_cm",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles",
        "shoulders_length_cm",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "user_profiles", "breast_length_cm", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_profiles", "hips_length_cm", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_profiles", "waist_length_cm", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_profiles", "leg_length_cm", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_profiles", "height_cm", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("user_profiles", "birth_date")
    op.drop_column("user_profiles", "phone_number")
    op.drop_column("user_profiles", "last_name")
    op.drop_column("user_profiles", "first_name")
    # ### end Alembic commands ###
