"""Create 'items', 'size_charts', 'item_measurements', 'favorites', 'fitview_events' tables

Revision ID: edfd5a4e2a6c
Revises: cc227966db04
Create Date: 2026-04-05 17:33:57.033553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfd5a4e2a6c'
down_revision: Union[str, Sequence[str], None] = 'cc227966db04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DRESS', 'SKIRT', 'T_SHIRT', 'BLOUSE', 'PANTS', 'SHIRT', name='itemcategoryenum'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('reference_point', sa.String(length=255), nullable=False),
    sa.Column('ref_coefficient', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_brand'), 'items', ['brand'], unique=False)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('used_fitview', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('fitview_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.Column('height_used_cm', sa.Float(), nullable=True),
    sa.Column('result_end_cm', sa.Float(), nullable=True),
    sa.Column('result_label', sa.String(length=10), nullable=True),
    sa.Column('ab_group', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitview_events_id'), 'fitview_events', ['id'], unique=False)
    op.create_table('item_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('total_length_cm', sa.Float(), nullable=False),
    sa.Column('inseam_cm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_measurements_id'), 'item_measurements', ['id'], unique=False)
    op.create_table('size_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('waist_min_cm', sa.Integer(), nullable=False),
    sa.Column('waist_max_cm', sa.Integer(), nullable=False),
    sa.Column('breast_min_cm', sa.Integer(), nullable=False),
    sa.Column('breast_max_cm', sa.Integer(), nullable=False),
    sa.Column('shoulders_min_cm', sa.Integer(), nullable=False),
    sa.Column('shoulders_max_cm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_charts_breast_max_cm'), 'size_charts', ['breast_max_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_breast_min_cm'), 'size_charts', ['breast_min_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_id'), 'size_charts', ['id'], unique=False)
    op.create_index(op.f('ix_size_charts_item_id'), 'size_charts', ['item_id'], unique=False)
    op.create_index(op.f('ix_size_charts_shoulders_max_cm'), 'size_charts', ['shoulders_max_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_shoulders_min_cm'), 'size_charts', ['shoulders_min_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_waist_max_cm'), 'size_charts', ['waist_max_cm'], unique=False)
    op.create_index(op.f('ix_size_charts_waist_min_cm'), 'size_charts', ['waist_min_cm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_charts_waist_min_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_waist_max_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_shoulders_min_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_shoulders_max_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_item_id'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_id'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_breast_min_cm'), table_name='size_charts')
    op.drop_index(op.f('ix_size_charts_breast_max_cm'), table_name='size_charts')
    op.drop_table('size_charts')
    op.drop_index(op.f('ix_item_measurements_id'), table_name='item_measurements')
    op.drop_table('item_measurements')
    op.drop_index(op.f('ix_fitview_events_id'), table_name='fitview_events')
    op.drop_table('fitview_events')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index(op.f('ix_items_brand'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
