apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fitview.fullname" . }}-db-policy
  labels:
    {{- include "fitview.labels" . | nindent 4 }}
spec:
  # Применяем политику к подам с меткой database
  podSelector:
    matchLabels:
      {{- include "fitview.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
  ingress:
    # Разрешаем входящий трафик только от пода бэкенда
    - from:
        - podSelector:
            matchLabels:
              {{- include "fitview.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 5432
