apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  PGPASSWORD: {{ .Values.secrets.PGPASSWORD | quote }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.STRIPE_SECRET_KEY | quote }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.secrets.STRIPE_PUBLISHABLE_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.STRIPE_WEBHOOK_SECRET | quote }}