apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PGPASSWORD: {{ .Values.secrets.PGPASSWORD | quote }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.STRIPE_SECRET_KEY | quote }}
