apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fitview.fullname" . }}-backend
  labels:
    {{- include "fitview.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fitview.fullname" . }}-frontend
  labels:
    {{- include "fitview.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
