apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fitview.fullname" . }}-db
  labels:
    {{- include "fitview.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "fitview.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "fitview.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "fitview.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.database.port }}
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName | quote }}
            # Временное решение, позже заменим на Secret
            - name: POSTGRES_PASSWORD
              value: "password"
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
          volumeMounts:
            - name: db-data
              mountPath: {{ .Values.database.storage.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.database.storage.size }}
