apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.beat | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: beat
          image: {{ .Values.images.backend }}
          command: ["celery", "-A", "core.celery_app", "beat", "--loglevel=info", "-s", "/tmp/celerybeat-schedule"]
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: static-data
              mountPath: /app/static
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)"
          resources:
            {{- toYaml .Values.resources.beat | nindent 12 }}
      volumes:
        - name: static-data
          emptyDir: {}
