apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: beat
          image: {{ .Values.images.backend }}
          command: ["celery", "-A", "core.celery_app", "beat", "--loglevel=info"]
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)"
          resources:
            limits: { cpu: 200m, memory: 256Mi }
            requests: { cpu: 50m, memory: 128Mi }
