apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mailhog
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: {{ .Values.images.mailhog }}
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            limits: { cpu: 100m, memory: 128Mi }
            requests: { cpu: 25m, memory: 32Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailhog
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: ui
      port: 8025
      targetPort: 8025
